In [1]:
import numpy as np
from typing import Literal

from solver_back import *

In [2]:
snake2 = [2,2,2,2,2,2,2]
snake3 = [3,2,2,3,2,3,2,2,3,3,2,2,2,3,3,3,3]
snake4 = [2,4,2,2,2,2,2,2,2,2,2,3,2,4,2,2,2,4,3,2,2,2,2,2,3,3,2,2,2,2,2,2,2,2,3,2,3,2,3,2,4,2,2,3,2,3]

def sum_valid(snake:list,cube_size=3):
    # print(sum(snake)-len(snake) + 1 - cube_size**3)
    return sum(snake)-len(snake) + 1 == cube_size ** 3

print("snake2 ok :",sum_valid(snake2,cube_size=2))
print("snake3 ok :",sum_valid(snake3,cube_size=3))
print("snake4 ok :",sum_valid(snake4,cube_size=4))

snake2 ok : True
snake3 ok : True
snake4 ok : True


In [3]:
cube_sol = solve(snake3,size=3,start_point=(0,0,1))

#16
#15
#14
#.#13
#12
#11
#10
#9
##############8
#.#.#.#.#7
#6
#5
#4
######3
##.......##......##.......##.....

In [4]:
plot_cube(cube_sol)

In [5]:
print("list_dir :")
print(cube_sol.list_dir)
print("------------")
print(cube_sol.M)

list_dir :
['y', '-z', '-y', 'x', 'z']
------------
[[[0 1 0]
  [1 1 0]
  [1 1 0]]

 [[0 0 0]
  [1 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 1 0]
  [0 0 0]]]


In [6]:
# break_all = False
# for i in range(3):
#     if break_all : break
#     for j in range(3):
#         if break_all : break
#         for k in range(3):
#             if break_all : break
#             cube_sol = solve(snake4,size=4,start_point=(i,j,k))
#             print(f"\n=================({i},{j},{k})")
#             # if cube_sol is not None : break_all = True
#             if 0 not in cube_sol.M : break_all = True

In [10]:
cube_sol = solve(snake4,size=4,start_point=(0,0,1),stop_len=0)

#45
#44
#43
#42
#41
#40
#39
#38
#37
#36
#35
#34
#33
#.#.#.#32
#31
#30
#29
##28
#27
#26
#25
#24
#23
#22
#21
#20
#19
#18
#17
#16
#15
#14
#13
#12
#11
#10
#9
####8
#####7
#6
###.......###...............................##.##....#####...############....#######################........#..#.#....###.................#.#..#.#.#.#.#####################........#########.####.##....##############.#.#.###.#.#####.#.#.###.#................############.########.######5
#4
####..##..................................................................................................................................................................................................................................................................................................................................................................................................................##................................................................................................................................

In [8]:
plot_cube(cube_sol,start_point=(0,0,0))

In [9]:
print(cube_sol.list_dir)
print(f"cube size = {cube_sol.size}")
print(cube_sol.prev_dir)
print(cube_sol.M)

['x', 'y', 'x', '-y', 'x', 'y', 'z', '-x', '-y', 'x', '-y', 'z', '-y', '-z', 'y', '-x', '-y', 'z', '-x', 'y', '-z', '-y', '-z', 'y', 'x', 'z', '-x', '-z', 'y', 'x', 'y', 'x', '-y', 'z', '-x', 'y', '-z', '-x', 'z', '-y', '-z']
cube size = 4
-z
[[[1 1 1 1]
  [0 1 1 1]
  [1 1 1 1]
  [0 1 1 1]]

 [[1 0 0 1]
  [1 1 1 1]
  [1 0 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 0]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 0]]]


In [ ]:
size = 4
start_point = (0,0,0)
cube_init = T_cube( M = np.zeros((size,size,size), dtype=np.int8),
                end_pointer = start_point,
                prev_dir=None,
                size=size)

In [ ]:
print(cube_init.size)

# Amelioration

In [ ]:
def test_no_isolated_blocks(cube:T_cube,M:np.ndarray,cube_size:int):
    M = cube.M.copy()
    cube_size = cube.size
    while new_neighboor_to_99(M,cube_size): pass
    return 0 not in M
    


def new_neighboor_to_99(M:np.ndarray,cube_size:int):
    N1,N2,N3 = M.shape()
    modif = False
    for x in range(N1):
        for y in range(N2):
            for z in range(N3):
                if M[x,y,z]==99 : 
                    for xx,yy,zz in neighboor((x,y,z),cube_size):
                        if M[xx,yy,zz]:
                            modif = True
                            M[xx,yy,zz]=99
    return modif
                    


def neighboor(index:tuple[int],cube_size:int):
    x,y,z = index
    arr_index = np.array(index)
    Vx = np.array([1,0,0])
    Vy = np.array([0,1,0])
    Vz = np.array([0,0,1])

    n1 = arr_index + Vx
    n2 = arr_index + Vy
    n3 = arr_index + Vz
    n4 = arr_index - Vx
    n5 = arr_index - Vy
    n6 = arr_index - Vz

    l = [   neigh
            for neigh in [n1, n2, n3, n4, n5, n6]
            if -1 not in neigh and cube_size not in neigh]
    return l

