In [50]:
import numpy as np
from typing import Literal

from solver_back import *

In [57]:
snake3 = [3,2,2,3,2,3,2,2,3,3,2,2,2,3,3,3,3]
snake4 = [2,4,2,2,2,2,2,2,2,2,2,3,2,4,2,2,2,4,3,2,2,2,2,2,3,3,2,2,2,2,2,2,2,2,3,2,3,2,3,2,4,2,2,3,2,3]
snake4 = [3,2,3,2,2,4,2,3,2,3,2,3,2,2,2,2,2,2,2,2,2,2,3,3,2,2,2,2,2,3,4,2,2,2,4,2,3,2,2,2,2,2,2,2,2,2,4,2]
# snake4 = [3,2,3,2,2,4,2,3,2,3,2,3,2,2,2,2,2,2,2,2,3,3,2,2,2,2,2,3,4,2,2,2,4,2,3,2,2,2,2,2,2,2,2,2,4,2]
snake2 = [2,2,2,2,2,2,2]
snake4.reverse()
snake3.reverse()

def sum_valid(snake:list,cube_size=3):
    print(sum(snake)-len(snake) + 1 - 4**3)
    return sum(snake)-len(snake) + 1 == cube_size ** 3
print("snake2 ok :",sum_valid(snake2,cube_size=2))
print("snake3 ok :",sum_valid(snake3,cube_size=3))
print("snake4 ok :",sum_valid(snake4,cube_size=4))

-56
snake2 ok : True
-37
snake3 ok : True
2
snake4 ok : False


In [52]:
cube_sol = solve(snake3,size=3,start_point=(0,0,0))

16
15
14
13
12
11
10
9
8
7
6
5
..4
3
2
1
0
..Solution


In [53]:
print(cube_sol.list_dir)
print(cube_sol.M)

['x', 'y', '-x', 'z', 'x', '-z', 'x', '-y', '-x', 'z', 'y', '-z', 'x', 'z', '-y', 'x', 'y']
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [55]:
cube_sol = solve(snake4,size=4,start_point=(0,0,3))

47
46
45
44
43
42
41
40
39
38
37
36
35
34
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

In [40]:
print(cube_sol.list_dir)
print(cube_sol.M)

AttributeError: 'NoneType' object has no attribute 'list_dir'